using System.Xml.Serialization;

namespace GameLauncher.Core.Models
{
    /// <summary>
    /// Represents a platform category in LaunchBox.
    /// Maps to PlatformCategory elements in Platforms.xml.
    /// Categories form a hierarchical navigation tree via Parents.xml.
    /// </summary>
    [XmlRoot("PlatformCategory")]
    public class PlatformCategory
    {
        public string Name { get; set; } = string.Empty;
        public string? NestedName { get; set; }
        public string? Notes { get; set; }
        public string? VideoPath { get; set; }
        public string? SortTitle { get; set; }
        public bool IsAutogenerated { get; set; }
        public string? ImageType { get; set; }
        public string? Category { get; set; }
        public string? LastGameId { get; set; }
        public string? BigBoxView { get; set; }
        public bool LocalDbParsed { get; set; }
        public string? BigBoxTheme { get; set; }
        public string? LastSelectedChild { get; set; }
        public bool HideInBigBox { get; set; }
    }
}
