using System;
using System.Xml.Serialization;

namespace GameLauncher.Core.Models
{
    /// <summary>
    /// Represents a playlist in LaunchBox.
    /// Maps to Playlist elements in Playlists/{Name}.xml.
    /// Each playlist file also contains PlaylistGame and PlaylistFilter entries.
    /// </summary>
    [XmlRoot("Playlist")]
    public class Playlist
    {
        public string PlaylistId { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string? NestedName { get; set; }
        public string? SortBy { get; set; }
        public string? Notes { get; set; }
        public string? VideoPath { get; set; }
        public string? ImageType { get; set; }
        public string? Category { get; set; }
        public string? BigBoxView { get; set; }
        public string? BigBoxTheme { get; set; }
        public bool IncludeWithPlatforms { get; set; }
        public bool AutoPopulate { get; set; }
        public string? SortTitle { get; set; }
        public bool IsAutogenerated { get; set; }
        public bool LocalDbParsed { get; set; }
        public string? Developer { get; set; }
        public string? Manufacturer { get; set; }
        public string? Cpu { get; set; }
        public string? Memory { get; set; }
        public string? Graphics { get; set; }
        public string? Sound { get; set; }
        public string? Display { get; set; }
        public string? Media { get; set; }
        public string? MaxControllers { get; set; }
        public string? Folder { get; set; }
        public string? VideosFolder { get; set; }
        public string? FrontImagesFolder { get; set; }
        public string? BackImagesFolder { get; set; }
        public string? ClearLogoImagesFolder { get; set; }
        public string? FanartImagesFolder { get; set; }
        public string? ScreenshotImagesFolder { get; set; }
        public string? BannerImagesFolder { get; set; }
        public string? SteamBannerImagesFolder { get; set; }
        public string? ManualsFolder { get; set; }
        public string? MusicFolder { get; set; }
        public string? ScrapeAs { get; set; }
        public string? LastSelectedChild { get; set; }
        public string? AndroidThemeVideoPath { get; set; }
        public bool HideInBigBox { get; set; }
    }
}
